name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo-site
  workflow_dispatch: # Allows manual trigger if needed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: "site/package-lock.json"

      - name: Install Node Dependencies
        run: npm ci
        working-directory: site

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.162.1"
          extended: true

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Make script executable and Build Site
        run: bash site/scripts/build.sh

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
